### ISSUE TITLE
is there a way to shortcut downloading models (again?)

### ISSUE THREAD

**Issue by johndpope** [SHI-Labs/Text2Video-Zero-sd-webui#1]
have this working locally already without webui - can I paste over the models?

**Comment by ericlormul** [comment]
it may work out of the box without redownloading if you have successfully used the original demo, since I just packed the original demo into webui without changing its model loading logic.

**Comment by johndpope** [comment]
I gave up on this - had to delete it - everytime I started webui - there'd be a download or caching - it always started - but always kept trying to repeat.
